import type { AnalyticsKnowledgePack } from './analyticsKnowledgeTypes';
import clickhouseSchemaFirst from './analyticsKnowledge/platform/clickhouse/schema-first.md?raw';
import clickhouseQuerySafety from './analyticsKnowledge/platform/clickhouse/query-safety.md?raw';
import googleAnalyticsMetricSemantics from './analyticsKnowledge/platform/google-analytics/metric-semantics.md?raw';
import googleSheetsStructureDetection from './analyticsKnowledge/platform/google-sheets/structure-detection.md?raw';
import postgresqlSchemaFirst from './analyticsKnowledge/platform/postgresql/schema-first.md?raw';
import generalAnalysisPlaybook from './analyticsKnowledge/general-analysis/analysis-playbook.md?raw';

export const BUILT_IN_ANALYTICS_KNOWLEDGE_PACKS: AnalyticsKnowledgePack[] = [
  {
    id: 'platform.clickhouse',
    layer: 'platform',
    title: 'ClickHouse platform knowledge',
    version: 1,
    checksum: 'builtin-platform-clickhouse-v1',
    status: 'active',
    rules: [
      {
        id: 'platform.clickhouse.schema_first',
        layer: 'platform',
        type: 'connector_rule',
        title: 'Inspect ClickHouse schema before querying',
        description: 'Use real database-qualified tables and schema discovery before writing ClickHouse SQL.',
        version: 1,
        status: 'active',
        priority: 90,
        triggers: { connectors: ['clickhouse'] },
        body: clickhouseSchemaFirst,
      },
      {
        id: 'platform.clickhouse.query_safety',
        layer: 'platform',
        type: 'connector_rule',
        title: 'Write ClickHouse-safe analytical queries',
        description: 'Prefer deterministic ClickHouse patterns for date filtering, grouping, and chartable results.',
        version: 1,
        status: 'active',
        priority: 82,
        triggers: { connectors: ['clickhouse'] },
        dependsOn: ['platform.clickhouse.schema_first'],
        body: clickhouseQuerySafety,
      },
    ],
  },
  {
    id: 'platform.google-analytics',
    layer: 'platform',
    title: 'Google Analytics platform knowledge',
    version: 1,
    checksum: 'builtin-platform-google-analytics-v1',
    status: 'active',
    rules: [
      {
        id: 'platform.google_analytics.metric_semantics',
        layer: 'platform',
        type: 'connector_rule',
        title: 'Respect GA metric and dimension semantics',
        description: 'Use only described GA dimensions and metrics, with native GA date handling.',
        version: 1,
        status: 'active',
        priority: 84,
        triggers: { connectors: ['google-analytics'] },
        body: googleAnalyticsMetricSemantics,
      },
    ],
  },
  {
    id: 'platform.google-sheets',
    layer: 'platform',
    title: 'Google Sheets platform knowledge',
    version: 1,
    checksum: 'builtin-platform-google-sheets-v1',
    status: 'active',
    rules: [
      {
        id: 'platform.google_sheets.structure_detection',
        layer: 'platform',
        type: 'connector_rule',
        title: 'Verify Google Sheets structure before analysis',
        description: 'Treat imported sheet ranges as user-authored data that may need header and type validation.',
        version: 1,
        status: 'active',
        priority: 76,
        triggers: { connectors: ['google-sheets'] },
        body: googleSheetsStructureDetection,
      },
    ],
  },
  {
    id: 'platform.postgresql',
    layer: 'platform',
    title: 'PostgreSQL platform knowledge',
    version: 1,
    checksum: 'builtin-platform-postgresql-v1',
    status: 'active',
    rules: [
      {
        id: 'platform.postgresql.schema_first',
        layer: 'platform',
        type: 'connector_rule',
        title: 'Inspect PostgreSQL schema before querying',
        description: 'Use schema-aware SQL and avoid assumptions about table names or join keys.',
        version: 1,
        status: 'active',
        priority: 78,
        triggers: { connectors: ['postgresql'] },
        body: postgresqlSchemaFirst,
      },
    ],
  },
  {
    id: 'general.data-analysis',
    layer: 'general-analysis',
    title: 'General data analysis knowledge',
    version: 1,
    checksum: 'builtin-general-data-analysis-v1',
    status: 'active',
    rules: [
      {
        id: 'general.analysis.workflow',
        layer: 'general-analysis',
        type: 'analysis_practice',
        title: 'Use a schema-first analytical workflow',
        description: 'Understand metric intent, inspect data, calculate with tools, then summarize.',
        version: 1,
        status: 'active',
        priority: 70,
        triggers: { always: true },
        body: generalAnalysisPlaybook,
      },
      {
        id: 'general.analysis.verification',
        layer: 'general-analysis',
        type: 'verification_method',
        title: 'Verify before presenting insight',
        description: 'Cross-check denominators, filters, date windows, and result scale before finalizing.',
        version: 1,
        status: 'active',
        priority: 88,
        triggers: { always: true },
        body: generalAnalysisPlaybook,
      },
      {
        id: 'general.analysis.fallacy_guards',
        layer: 'general-analysis',
        type: 'fallacy_guard',
        title: 'Guard against common analytical fallacies',
        description: 'Prevent misleading results from aggregation, joins, and unsupported causal claims.',
        version: 1,
        status: 'active',
        priority: 86,
        triggers: { always: true },
        body: generalAnalysisPlaybook,
      },
      {
        id: 'general.analysis.auditability',
        layer: 'general-analysis',
        type: 'analysis_practice',
        title: 'Prefer auditable intermediate artifacts',
        description: 'Make analysis inspectable through briefs, hidden query results, and visible lineage when useful.',
        version: 1,
        status: 'active',
        priority: 80,
        triggers: { always: true },
        body: generalAnalysisPlaybook,
      },
    ],
  },
];
